# 说明平台是ios，版本是8.0
platform :ios, '8.0'

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

use_frameworks!


target 'TCShanXun' do
    pod 'SDWebImage'
    pod 'LTScrollView', '~> 0.1.7'
    pod 'MJRefresh', '~> 3.1.14.1'
    pod 'SDAutoLayout', '~> 2.1.3'
end

target 'TodayExtension' do
    pod 'SDWebImage'
end

